// todo: remove mock functionality
import type { Restaurant, Category, MenuItem } from './types';

export const mockRestaurant: Restaurant = {
  id: '1',
  name: 'La Bella Cucina',
  description: 'Authentic Italian cuisine crafted with passion and the finest ingredients. Our family recipes have been passed down through generations, bringing the true taste of Italy to your table.',
  address: '123 Main Street, Downtown',
  phone: '+1 (555) 123-4567',
  email: 'info@labellacucina.com',
  hours: 'Mon-Thu: 11am-10pm | Fri-Sat: 11am-11pm | Sun: 12pm-9pm',
};

export const mockCategories: Category[] = [
  { id: '1', name: 'Appetizers', nameEs: 'Aperitivos', nameFr: 'Entrées', order: 1 },
  { id: '2', name: 'Main Courses', nameEs: 'Platos Principales', nameFr: 'Plats Principaux', order: 2 },
  { id: '3', name: 'Desserts', nameEs: 'Postres', nameFr: 'Desserts', order: 3 },
  { id: '4', name: 'Beverages', nameEs: 'Bebidas', nameFr: 'Boissons', order: 4 },
];

export const mockMenuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Bruschetta',
    nameEs: 'Bruschetta',
    nameFr: 'Bruschetta',
    description: 'Toasted bread topped with fresh tomatoes, basil, and garlic',
    descriptionEs: 'Pan tostado con tomates frescos, albahaca y ajo',
    descriptionFr: 'Pain grillé garni de tomates fraîches, basilic et ail',
    price: 9.99,
    categoryId: '1',
    available: true,
  },
  {
    id: '2',
    name: 'Calamari Fritti',
    nameEs: 'Calamares Fritos',
    nameFr: 'Calamars Frits',
    description: 'Crispy fried squid served with marinara sauce',
    descriptionEs: 'Calamares crujientes servidos con salsa marinara',
    descriptionFr: 'Calamars croustillants servis avec sauce marinara',
    price: 14.99,
    categoryId: '1',
    available: true,
  },
  {
    id: '3',
    name: 'Spaghetti Carbonara',
    nameEs: 'Espagueti Carbonara',
    nameFr: 'Spaghetti Carbonara',
    description: 'Classic pasta with pancetta, egg, parmesan, and black pepper',
    descriptionEs: 'Pasta clásica con panceta, huevo, parmesano y pimienta negra',
    descriptionFr: 'Pâtes classiques avec pancetta, œuf, parmesan et poivre noir',
    price: 18.99,
    categoryId: '2',
    available: true,
  },
  {
    id: '4',
    name: 'Margherita Pizza',
    nameEs: 'Pizza Margherita',
    nameFr: 'Pizza Margherita',
    description: 'Traditional pizza with fresh mozzarella, tomatoes, and basil',
    descriptionEs: 'Pizza tradicional con mozzarella fresca, tomates y albahaca',
    descriptionFr: 'Pizza traditionnelle avec mozzarella fraîche, tomates et basilic',
    price: 16.99,
    categoryId: '2',
    available: true,
  },
  {
    id: '5',
    name: 'Grilled Salmon',
    nameEs: 'Salmón a la Parrilla',
    nameFr: 'Saumon Grillé',
    description: 'Fresh Atlantic salmon with lemon herb butter and vegetables',
    descriptionEs: 'Salmón del Atlántico con mantequilla de hierbas y limón',
    descriptionFr: 'Saumon de l\'Atlantique avec beurre aux herbes et citron',
    price: 24.99,
    categoryId: '2',
    available: true,
  },
  {
    id: '6',
    name: 'Tiramisu',
    nameEs: 'Tiramisú',
    nameFr: 'Tiramisu',
    description: 'Classic Italian dessert with espresso-soaked ladyfingers',
    descriptionEs: 'Postre italiano clásico con bizcochos empapados en espresso',
    descriptionFr: 'Dessert italien classique avec biscuits imbibés d\'espresso',
    price: 8.99,
    categoryId: '3',
    available: true,
  },
  {
    id: '7',
    name: 'Panna Cotta',
    nameEs: 'Panna Cotta',
    nameFr: 'Panna Cotta',
    description: 'Creamy vanilla custard with berry compote',
    descriptionEs: 'Crema de vainilla con compota de frutos rojos',
    descriptionFr: 'Crème vanille avec compote de fruits rouges',
    price: 7.99,
    categoryId: '3',
    available: true,
  },
  {
    id: '8',
    name: 'Italian Soda',
    nameEs: 'Soda Italiana',
    nameFr: 'Soda Italien',
    description: 'Refreshing sparkling water with your choice of syrup',
    descriptionEs: 'Agua con gas refrescante con jarabe a elección',
    descriptionFr: 'Eau pétillante rafraîchissante avec sirop au choix',
    price: 4.99,
    categoryId: '4',
    available: true,
  },
  {
    id: '9',
    name: 'Espresso',
    nameEs: 'Espresso',
    nameFr: 'Espresso',
    description: 'Rich Italian espresso, single or double shot',
    descriptionEs: 'Espresso italiano rico, simple o doble',
    descriptionFr: 'Espresso italien riche, simple ou double',
    price: 3.99,
    categoryId: '4',
    available: true,
  },
];
