ALTER TABLE languages ADD COLUMN IF NOT EXISTS native_name TEXT DEFAULT '';
ALTER TABLE languages ADD COLUMN IF NOT EXISTS direction TEXT DEFAULT 'ltr';
ALTER TABLE languages ADD COLUMN IF NOT EXISTS flag_image TEXT;
ALTER TABLE languages ADD COLUMN IF NOT EXISTS is_default BOOLEAN DEFAULT false;
