ALTER TABLE settings 
ADD COLUMN IF NOT EXISTS kd_show_table_number BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS kd_show_order_time BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS kd_show_clock BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS kd_show_notes BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS kd_has_pending_status BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS kd_show_recently_completed BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS kd_pending_color TEXT NOT NULL DEFAULT '#FF9800',
ADD COLUMN IF NOT EXISTS kd_preparing_color TEXT NOT NULL DEFAULT '#2196F3',
ADD COLUMN IF NOT EXISTS kd_ready_color TEXT NOT NULL DEFAULT '#4CAF50',
ADD COLUMN IF NOT EXISTS currency_name TEXT NOT NULL DEFAULT 'US Dollar',
ADD COLUMN IF NOT EXISTS currency_symbol TEXT NOT NULL DEFAULT '$',
ADD COLUMN IF NOT EXISTS currency_position TEXT NOT NULL DEFAULT 'after',
ADD COLUMN IF NOT EXISTS currency_select TEXT NOT NULL DEFAULT 'USD';
