ALTER TABLE settings 
ADD COLUMN IF NOT EXISTS kd_show_table_number BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS kd_show_order_time BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS kd_show_clock BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS kd_show_notes BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS kd_has_pending_status BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS kd_show_recently_completed BOOLEAN NOT NULL DEFAULT true;
